.MODEL SMALL
.STACK 100H

.DATA
STR DB "This is inside the procedure$"

.CODE 
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX    
    
    CALL MESG ; AT THIS POINT, THE NEXT LINE IS PUSHED ON THE STACK (THE LINE THAT IS SUPPOSED TO EXECUTE AFTER PROCEDURE CALL)
    
    MOV AH, 4CH
    INT 21H
MAIN ENDP  

MESG PROC
    MOV AH, 9    
    LEA DX, STR
    INT 21H            
RET   ; POP THE LINE THAT MUST BE EXECUTED AFTER THE MESG PROCEDURE 
MESG ENDP
    END MAIN